#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    Fix eduroam for Arch-based Linux
# ---------------------------------------------------------------------------- #
_usage() {
  echo "Usage: eduroam <wifi-name>"
}

if [ "$#" -lt 1 ]; then
  _usage
  exit 1
elif [ "$1" == "--help" ]; then
  _usage
  exit 0
fi
nmcli connection modify $1 802-1x.phase1-auth-flags 32
echo "[INFO] Setting phase1-auth-flags=32 for $1"
echo "[INFO] Restarting Network Manager..."
sudo systemctl restart NetworkManager
echo "[INFO] Done"
