#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    Modify the Exec line in a .desktop file to enable Wayland
# ---------------------------------------------------------------------------- #
_usage() {
  echo "Usage: enable-wayland <desktop_file>"
}

if [ $# -eq 0 ]; then
  _usage
  exit 1
fi

sudo -v
desktop_file=$1

if [ ! -f "$desktop_file" ]; then
  echo "File $desktop_file does not exist."
  exit 1
fi

while IFS= read -r line; do
  if [[ $line == Exec* ]]; then
    if [[ $line == *"%U" ]]; then
      modified_line="${line//\%U/--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime \%U}"
    elif [[ $line == *"%F" ]]; then
      modified_line="${line//\%F/--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime \%F}"
    else
      modified_line="$line"
    fi
  else
    modified_line="$line"
  fi
done <"$desktop_file" | sudo tee "$desktop_file.tmp" >/dev/null

sudo mv "$desktop_file.tmp" "$desktop_file"
cat "$desktop_file"
