#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    Modify the Exec line in a .desktop file to enable Wayland
# ---------------------------------------------------------------------------- #
if [ $# -eq 0 ]; then
  echo "Usage: $0 <file_path>"
  exit 1
fi

sudo -v
file_path=$1

if [ ! -f "$file_path" ]; then
  echo "File $file_path does not exist."
  exit 1
fi

while IFS= read -r line; do
  if [[ $line == Exec* ]]; then
    if [[ $line == *"%U" ]]; then
      modified_line="${line//\%U/--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime \%U}"
    elif [[ $line == *"%F" ]]; then
      modified_line="${line//\%F/--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime \%F}"
    else
      modified_line="$line"
    fi
  else
    modified_line="$line"
  fi
done <"$file_path" | sudo tee "$file_path.tmp" >/dev/null

sudo mv "$file_path.tmp" "$file_path"
cat "$file_path"
