#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    Mount or unmount iPhone via ifuse
# ---------------------------------------------------------------------------- #

_usage() {
  echo "Usage: iPhone [-m|-u|-h|--help]"
  echo "  -m: mount iPhone"
  echo "  -u: unmount iPhone"
  echo "  -h, --help: show this help message"
}

if ! command -v ifuse /dev/null 2>&1; then
  echo "Error: ifuse is required."
  exit 1
fi

operation=$1
if [ $# -eq 0 ]; then
  _usage
  exit 1
fi
if [ $operation == "-m" ]; then
  mkdir -p ~/iPhone
  ifuse ~/iPhone
  if [ $? -eq 0 ]; then
    echo "Mounted at ~/iPhone!"
  fi
  echo "Mounted at ~/iPhone!"
elif [ $operation == "-u" ]; then
  if [ ! -d ~/iPhone ]; then
    echo "~/iPhone does not exist."
    exit 1
  else
    umount ~/iPhone
    if [ $? -eq 0 ]; then
      rm -rf ~/iPhone
      echo "Unmounted!"
    fi
  fi
elif [ $operation == "-h" ] || [ $operation == "--help" ]; then
  _usage
else
  _usage
  exit 1
fi
