#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    Create a new LeetCode POTD python solution file via alfa-leetcode-api
#    User should modify the directory based on their own setup
# ---------------------------------------------------------------------------- #
solution_dir="$HOME/GitHub/LeetCode"
mkdir -p $solution_dir

for cmd in docker jq nano curl; do
  if ! command -v $cmd 2>&1 >/dev/null; then
    echo "Error: $cmd is not installed."
    exit 1
  fi
done
if ! docker container ls -a --format '{{.Names}}' | grep -q '^alfa-leetcode-api$'; then
  docker container create --name alfa-leetcode-api -p 3000:3000 alfaarghya/alfa-leetcode-api:2.0.1
fi
echo "Starting alfa-leetcode-api server..."
docker start alfa-leetcode-api >/dev/null

echo "Fetching data from http://localhost:3000/daily..."

daily=$(curl -s --retry 10 --retry-all-errors --retry-delay 1 http://localhost:3000/daily)
if [ $? -ne 0 ]; then
  echo "Error: Failed to fetch data from http://localhost:3000/daily"
  docker stop alfa-leetcode-api >/dev/null
  exit 1
fi

titleSlug=$(echo "$daily" | jq -r '.titleSlug')
questionFrontendId=$(echo "$daily" | jq -r '.questionFrontendId')
questionFrontendId=$(printf "%04d" $questionFrontendId)
filename="$questionFrontendId-$titleSlug"

echo "Completed. Shutting down alfa-leetcode-api server..."
docker stop alfa-leetcode-api >/dev/null

cd "$solution_dir/daily"
if [ -e "$filename.py" ]; then
  echo "The file "$filename.py" already existed. Exiting"
  exit 1
fi
touch "$filename.py"
nano "$filename.py"

if [ ! -s "$filename.py" ]; then
  echo "The file $filename.py is empty. Removing"
  rm "$filename.py"
  exit 1
fi

git add "$filename.py"
git commit -m "add: daily question $(date +%F)"
git push
