#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    Create a new LeetCode POTD python solution file via alfa-leetcode-api
#    User should modify the directory based on their own setup
# ---------------------------------------------------------------------------- #
solution_dir="$HOME/GitHub/LeetCode"
mkdir -p $solution_dir

deps=("docker" "jq" "nano" "curl")
missing_deps=()
for dep in "${deps[@]}"; do
  if ! pacman -Qi "$dep" &>/dev/null; then
    missing_deps+=("$dep")
  fi
done
if [ ${#missing_deps[@]} -ne 0 ]; then
  echo "[ERROR] Missing dependencies: ${missing_deps[*]}"
  exit 1
fi

if ! docker container ls -a --format '{{.Names}}' | grep -q '^alfa-leetcode-api$'; then
  docker container create --name alfa-leetcode-api -p 3000:3000 alfaarghya/alfa-leetcode-api:2.0.1
fi
echo "[INFO] Starting alfa-leetcode-api server..."
docker start alfa-leetcode-api >/dev/null

echo "[INFO] Fetching data from http://localhost:3000/daily..."

daily=$(curl -s --retry 10 --retry-all-errors --retry-delay 1 http://localhost:3000/daily)
if [ $? -ne 0 ]; then
  echo "[ERROR] Failed to fetch data from http://localhost:3000/daily"
  docker stop alfa-leetcode-api >/dev/null
  exit 1
fi

titleSlug=$(echo "$daily" | jq -r '.titleSlug')
questionFrontendId=$(echo "$daily" | jq -r '.questionFrontendId')
questionFrontendId=$(printf "%04d" $questionFrontendId)
filename="$questionFrontendId-$titleSlug"

echo "[INFO] Completed. Shutting down alfa-leetcode-api server..."
docker stop alfa-leetcode-api >/dev/null

cd "$solution_dir/daily"
if [ -e "$filename.py" ]; then
  echo "[ERROR] The file "$filename.py" already existed. Exiting"
  exit 1
fi
touch "$filename.py"
nano "$filename.py"

if [ ! -s "$filename.py" ]; then
  echo "[ERROR] The file $filename.py is empty. Removing"
  rm "$filename.py"
  exit 1
fi

git add "$filename.py"
git commit -m "add: daily question $(date +%F)"
git push
