#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    Create a new LeetCode python solution file at $PWD
#    And apply black formatting if available
# ---------------------------------------------------------------------------- #

file="$HOME/Scripts/problems_all.json"
source="https://raw.githubusercontent.com/bunnyxt/lcid/refs/heads/main/problems_all.json"

_usage() {
  echo "Usage: lc-new [--refresh] <question_id>"
}

if [ -z "$1" ]; then
  _usage
  exit 1
fi

for cmd in jq nano curl; do
  if ! command -v $cmd 2&>1 /dev/null; then
    echo "Error: $cmd is not installed."
    exit 1
  fi
done

if [ "$1" == "--refresh" ]; then
  echo ":: Refreshing problem set..."
  curl -s -o "$file" "$source"

  if [ $? -eq 0 ]; then # checks the exit status of the last executed command
    if command -v prettier 2>&1 >/dev/null; then
      prettier $file --log-level silent -w
    fi
    echo ":: Succeeded."
    exit 0
  else
    echo ":: Failed to download the JSON file."
    exit 1
  fi
fi

if [ -z "$1" ]; then
  _usage
  exit 1
fi

if [ ! -f "$file" ]; then
  echo ":: File $file not found. You can refresh it using --refresh."
  exit 1
fi

data=$(cat "$file")
question_id=$1
title_slug=$(echo "$data" | jq -r --arg qid "$question_id" '.[$qid].titleSlug')
question_id=$(printf "%04d" $question_id)
new_py_file="$PWD/$question_id-$title_slug.py"

if [ "$titleSlug" == "null" ]; then
  echo ":: Question ID $question_id not found."
else
  touch "$new_py_file"
  nano "$new_py_file"
  if command -v black 2>&1 >/dev/null; then
    echo ":: Running black formatter on the following files:"
    echo "   - $new_py_file"
    black "$new_py_file" -l 100 -q
    echo ":: Black formatting applied."
  fi
fi
