#!/bin/bash
if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
	hyprlock -q &> /dev/null &
	disown
elif [[ $XDG_CURRENT_DESKTOP == "GNOME" ]]; then
	dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock
else
  echo "Unknown session: $XDG_CURRENT_DESKTOP."
fi
