#!/bin/bash
set -e
if [ "$1" == "push" ]; then
    echo "Removing: .log .Rhistory .RData"
    cd ~/Stat/
    find . -name "*.log" -type f
    find . -name "*.log" -type f -delete
    find . -name "*.Rhistory" -type f
    find . -name "*.Rhistory" -type f -delete
    find . -name "*.RData" -type f
    find . -name "*.RData" -type f -delete
    echo "Deletion completed. Proceed..."
    rclone sync ~/Stat/ gdrive:Stat/ --transfers 32 --checkers 64 -P --exclude=".git/" --exclude=".venv/" --exclude="__pycache__/"
elif [ "$1" == "pull" ]; then
    rclone sync gdrive:Stat/ ~/Stat/ --transfers 32 --checkers 64 -P
elif [ "$1" == "refresh" ]; then
    rclone config reconnect gdrive:
fi
