#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    Clean up __pycache__ directories and .python_history files
#    Recursively from the current directory
# ---------------------------------------------------------------------------- #
use_trash=false
if command -v trash 2>&1 >/dev/null; then
  use_trash=true
fi

pycache=$(find $(pwd) | grep -E "(/__pycache__$)" | grep -vE "(\.vscode|\.local|site-packages|\.cache)")
py_history=$(find $(pwd) | grep -E "(python_history$)" | grep -vE "(\.vscode|\.local|site-packages|\.cache)")
if [ -z "$pycache" ] && [ -z "$py_history" ]; then
  echo "No __pycache__ directories or .python_history files found"
  exit 0
fi
if [ -n "$pycache" ]; then
  echo "The following __pycache__ directories were found:"
  while IFS= read -r dir; do
    echo "  - $dir"
  done <<<"$pycache"
else
  echo "No __pycache__ directories found"
fi
if [ -n "$py_history" ]; then
  echo "The following .python_history files were found:"
  while IFS= read -r file; do
    echo "  - $file"
  done <<<"$py_history"
else
  echo "No .python_history files found"
fi

read -p "Do you want to delete all of these directories and files? (yes/no) [yes]: " confirm
confirm=${confirm:-yes}

if [ "$confirm" == "yes" ]; then
  if [ -n "$pycache" ]; then
    echo "$pycache" | while read -r dir; do
      if $use_trash; then
        if trash "$dir"; then
          echo "Deleted: $PWD/$dir"
        else
          echo "[ERROR] Failed to delete: $PWD/$dir"
        fi
      else
        if rm -rf "$dir"; then
          echo "Removed: $PWD/$dir"
        else
          echo "[ERROR] Failed to reomve: $PWD/$dir"
        fi
      fi
    done
  fi
  if [ -n "$py_history" ]; then
    echo "$py_history" | while read -r file; do
      if $use_trash; then
        if trash "$file"; then
          echo "Deleted: $PWD/$file"
        else
          echo "[ERROR] Failed to delete: $PWD/$file"
        fi
      else
        if rm -f "$file"; then
          echo "Removed: $PWD/$file"
        else
          echo "[ERROR] Failed to remove: $PWD/$file"
        fi
      fi
    done
  fi
else
  echo "Deletion aborted"
fi
