#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    Clean up __pycache__ directories and .python_history files
#    Recursively from the current directory
# ---------------------------------------------------------------------------- #
if ! pacman -Qi fd 2>&1 >/dev/null; then
  echo "[ERROR] fd is not installed"
  exit 1
fi

use_trash=false
if command -v trash 2>&1 >/dev/null; then
  use_trash=true
fi

pycache_dirs=$(fd -I --type d "__pycache__" --exclude=".pyenv" --exclude="pipx" --exclude="Trash" --exclude=".venv" --exclude=".vscode")
python_history_files=$(fd -I --type f "python_history" --exclude="Trash")
if [ -z "$pycache_dirs" ] && [ -z "$python_history_files" ]; then
  echo "[INFO] No __pycache__ directories or .python_history files found"
  exit 0
fi
if [ -n "$pycache_dirs" ]; then
  echo "[INFO] The following __pycache__ directories were found:"
  while IFS= read -r dir; do
    echo "        - $PWD/$dir"
  done <<<"$pycache_dirs"
else
  echo "[INFO] No __pycache__ directories found"
fi
if [ -n "$python_history_files" ]; then
  echo "[INFO] The following .python_history files were found:"
  while IFS= read -r file; do
    echo "        - $PWD/$file"
  done <<<"$python_history_files"
else
  echo "[INFO] No .python_history files found"
fi

read -p "Do you want to delete all of these directories and files? (yes/no) [yes]: " confirm
confirm=${confirm:-yes}

if [ "$confirm" == "yes" ]; then
  if [ -n "$pycache_dirs" ]; then
    echo "$pycache_dirs" | while read -r dir; do
      if $use_trash; then
        if trash "$dir"; then
          echo "[INFO] Deleted: $PWD/$dir"
        else
          echo "[ERROR] Failed to delete: $PWD/$dir"
        fi
      else
        if rm -rf "$dir"; then
          echo "[INFO] Removed: $PWD/$dir"
        else
          echo "[ERROR] Failed to reomve: $PWD/$dir"
        fi
      fi
    done
  fi
  if [ -n "$python_history_files" ]; then
    echo "$python_history_files" | while read -r file; do
      if $use_trash; then
        if trash "$file"; then
          echo "[INFO] Deleted: $PWD/$file"
        else
          echo "[ERROR] Failed to delete: $PWD/$file"
        fi
      else
        if rm -f "$file"; then
          echo "[INFO] Removed: $PWD/$file"
        else
          echo "[ERROR] Failed to remove: $PWD/$file"
        fi
      fi
    done
  fi
else
  echo "[INFO] Deletion aborted"
fi
