#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    Clean up __pycache__ directories and .python_history files
#    Recursively from the current directory
# ---------------------------------------------------------------------------- #
if ! command -v fd &>/dev/null; then
  echo "Error: fd is not installed."
  exit 1
fi

set -e
use_trash=false
if command -v trash &>/dev/null; then
  use_trash=true
fi

pycache_dirs=$(fd -H --type d "__pycache__" --exclude="pyenv" --exclude="pipx" --exclude="Trash")
python_history_files=$(fd -H --type f "python_history" --exclude="Trash")
if [ -z "$pycache_dirs" ] && [ -z "$python_history_files" ]; then
  echo "No __pycache__ directories or .python_history files found."
  exit 0
fi
if [ -n "$pycache_dirs" ]; then
  echo "The following __pycache__ directories were found:"
  while IFS= read -r dir; do
    echo "  - $PWD/$dir"
  done <<<"$pycache_dirs"
else
  echo "No __pycache__ directories found."
fi
if [ -n "$python_history_files" ]; then
  echo "The following .python_history files were found:"
  while IFS= read -r file; do
    echo "  - $PWD/$file"
  done <<<"$python_history_files"
else
  echo "No .python_history files found."
fi

read -p "Do you want to delete all of these directories and files? (yes/no) [yes]: " confirm
confirm=${confirm:-yes}

if [ "$confirm" == "yes" ]; then
  if [ -n "$pycache_dirs" ]; then
    echo "$pycache_dirs" | while read -r dir; do
      if $use_trash; then
        if trash "$dir"; then
          echo "Deleted: $dir"
        else
          echo "Failed to delete: $dir"
        fi
      else
        if rm -rf "$dir"; then
          echo "Removed: $dir"
        else
          echo "Failed to reomve: $dir"
        fi
      fi
    done
  fi
  if [ -n "$python_history_files" ]; then
    echo "$python_history_files" | while read -r file; do
      if $use_trash; then
        if trash "$file"; then
          echo "Deleted: $file"
        else
          echo "Failed to delete: $file"
        fi
      else
        if rm -f "$file"; then
          echo "Removed: $file"
        else
          echo "Failed to remove: $file"
        fi
      fi
    done
  fi
else
  echo "Deletion aborted."
fi
