#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    Clean up .Rhistory and .RData files
#    Recursively from the current directory
# ---------------------------------------------------------------------------- #
if ! command -v fd 2>&1 >/dev/null; then
  echo "[ERROR] fd is not installed."
  exit 1
fi

use_trash=false
if command -v trash 2>&1 >/dev/null; then
  use_trash=true
fi

files_to_delete=$(fd -H --type f "(Rhistory|RData)" --exclude "Trash" --exclude "R" --exclude "Telegram")
if [ -z "$files_to_delete" ]; then
  echo "[INFO] No .Rhistory or .RData files found"
  exit 0
fi
echo "[INFO] The following .Rhistory and .RData files were found:"
while IFS= read -r file; do
  echo "        - $PWD/$file"
done <<<"$files_to_delete"

read -p "Do you want to delete all of these files? (yes/no) [yes]: " confirm
confirm=${confirm:-yes}

if [ "$confirm" == "yes" ]; then
  echo "$files_to_delete" | while read -r file; do
    if $use_trash; then
      if trash "$file"; then
        echo "[INFO] Deleted: $PWD/$file"
      else
        echo "[ERROR] Failed to delete: $PWD/$file"
      fi
    else
      if rm -f "$file"; then
        echo "[INFO] Removed: $PWD/$file"
      else
        echo "[ERROR] Failed to remove: $PWD/$file"
      fi
    fi
  done
else
  echo "[INFO] Deletion aborted"
fi
