#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    Update submodules for the current repository
# ---------------------------------------------------------------------------- #
if [[ -n $(git status --porcelain) ]]; then
  echo "[ERROR] Commit all changes before updating submodules."
  exit 1
fi
git submodule update --remote
git add .
git commit -m 'submodule: update'
git push
