#!/bin/bash
# ---------------------------------------------------------------------------- #
#    Script made by hengtseChou
#    An rclone wrapper that syncs ~/Pictures to Google Drive or OneDrive
# ---------------------------------------------------------------------------- #
BLUE='\e[94m'
NC='\e[0m'

if ! command -v rclone 2>&1 >/dev/null; then
	echo "[ERROR] rclone is not installed."
	exit 1
fi

if [ "$1" == "push" ]; then
	echo -en "[INFO] Overwriting ${BLUE}**remote**${NC} storage. Proceed? (Y/n): "
	read -e -r response
	response=${response:-y}
	if [[ "$response" == "y" ]]; then
		if [[ "$2" == "--onedrive" ]]; then
			remote="onedrive"
		elif [[ "$2" == "--gdrive" ]] || [[ "$2" == "" ]]; then
			remote="gdrive"
		else
			echo "[ERROR] Invalid remote. Exiting."
			exit 1
		fi
		rclone sync ~/Pictures/ $remote:Pictures/ --transfers 16 --checkers 64 -P --exclude="Screenshots/"
	else
		echo "[INFO] Syncing canceled."
		exit 0
	fi
elif [ "$1" == "pull" ]; then
	echo -en "[INFO] Overwriting ${BLUE}**local**${NC} storage. Proceed? (Y/n): "
	read -e -r response
	response=${response:-y}
	if [[ "$response" == "y" ]]; then
		if [[ "$2" == "--onedrive" ]]; then
			remote="onedrive"
		elif [[ "$2" == "--gdrive" ]] || [[ "$2" == "" ]]; then
			remote="gdrive"
		else
			echo "[ERROR] Invalid remote. Exiting."
			exit 1
		fi
		rclone sync $remote:Pictures/ ~/Pictures --transfers 16 --checkers 64 -P
	else
		echo "[INFO] Syncing canceled."
		exit 0
	fi
else
	echo "Usage: $0 {push|pull} [--onedrive|--gdrive (default)]"
	exit 1
fi
